### ISSUE TITLE
Restrictive Answer in a Quiz

### ISSUE THREAD

**Issue by dandesantis14** [learn-co-curriculum/phase-1-quiz-working-with-objects-in-javascript#1]
### Canvas Link

https://learning.flatironschool.com/courses/4541/quizzes/22760

### Concern

Question on the quiz asked "Fill in the blank in the code above. What could I write to access the value for the first member's instruments?"

### Code Provided:
const artistInfo = {
  name: "Talking Heads",
  genre: "New Wave",
  origin: "New York City",
  members: [
    {
      firstName: "David",
      lastName: "Byrne",
      instruments: {
        main: "Vocals",
        secondary: "Guitar",
      },
    },
    {
      firstName: "Chris",
      lastName: "Frantz",
      instruments: {
        main: "Drums",
      },
    },
    {
      firstName: "Tina",
      lastName: "Weymouth",
      instruments: {
        main: "Bass",
      },
    },
    {
      firstName: "Jerry",
      lastName: "Harrison",
      instruments: {
        main: "Keyboards",
        secondary: "Guitar",
      },
    },
  ],
};

console.log(artistInfo.___________);
// => { main: "Vocals", secondary: "Guitar" }

### Problem:

Provided answer : members[0]["instruments"]

Was still marked incorrect. The only accepted answer is: _members[0].instruments_ but this is functionally the same as my provided answer.

### Suggested Changes

Add other solution possibility.

**Comment by lizbur10** [comment]
Hi @dandesantis14 ! Thank you for posting an issue and bringing this to our attention. The answer you identified has been added to the correct options. Apologies for the inconvenience!

Thanks for contributing to the Flatiron School curriculum 💙
