### ISSUE TITLE
Didn't accept answer with quotes

### ISSUE THREAD

**Issue by astania** [learn-co-curriculum/phase-1-quiz-working-with-objects-in-javascript#2]
## Link to Canvas

https://learning.flatironschool.com/courses/4599/quizzes/22759

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ x] Other (explain below)

### Source

```
In question 2, I initially submitted "Sweet potato" as my answer and it was marked incorrect. I took the test again and entered Sweet potato (without the quotation marks), and it was marked correct. 
```

## (Optional) Proposed Solution

Shouldn't both answers be correct answers? 

## What OS Are You Using?

- [ ] OS X
- [ x] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by lizbur10** [comment]
Hi @astania ! Thank you for bringing this to our attention! The acceptable responses have been updated accordingly.

💙
