### ISSUE TITLE
Returned the right answer, but was not given the point.

### ISSUE THREAD

**Issue by frantz3** [learn-co-curriculum/phase-1-quiz-working-with-objects-in-javascript#4]
### Canvas Link

https://my.learn.co/courses/514/quizzes/3556/history?version=1

### Concern

I got the second question correct, but I did not receive the point.

**Comment by lizbur10** [comment]
Hi @frantz3 - so sorry to hear that! If you can share with me exactly what you submitted as your answer, I can take a look. Thanks 🙂

**Comment by lizbur10** [comment]
Hi @frantz3 - I'm going to go ahead and close this issue. However, if you're able to provide more information about what you submitted, please feel free to reopen it. 💙
